import { useEffect, useState } from 'react';
import { Badge, Button, Card, Table } from '@urp/ui';
import { SupervisorApprovalModal } from './supervisor-approval-modal';
import { posDb, type Session } from './db';

type Sale = { id: string; deviceSaleId: string; cashierId: string; totalAmount: string; paymentMethod: string; status: 'completed' | 'voided' | 'refunded'; createdAt: string };
type Detail = Sale & { items: Array<{ id: string; productId: string; quantity: string; unitPrice: string; discountAmount: string }> };
const api = (path: string) => `${import.meta.env.VITE_API_URL ?? ''}/api/v1${path}`;

export function SaleHistory({ session, shiftId, online, onNotice }: { session: Session; shiftId?: string; online: boolean; onNotice: (message: string) => void }) {
  const [sales, setSales] = useState<Sale[]>([]);
  const [selected, setSelected] = useState<Detail | null>(null);
  const [approval, setApproval] = useState<{ id: string; actionType: string; context: string } | null>(null);
  const load = async () => { if (!online) return onNotice('Sale history requires a connection.'); const response = await fetch(api(`/sales${shiftId ? `?shiftId=${shiftId}` : ''}`), { headers: { Authorization: `Bearer ${session.accessToken}` } }); if (!response.ok) return onNotice('Could not load sale history.'); setSales((await response.json() as { sales: Sale[] }).sales); };
  useEffect(() => { void load(); }, [online, shiftId]);
  const open = async (sale: Sale) => { const response = await fetch(api(`/sales/${sale.id}`), { headers: { Authorization: `Bearer ${session.accessToken}` } }); if (response.ok) { const body = await response.json() as { sale: Detail; items: Detail['items'] }; setSelected({ ...body.sale, items: body.items }); } };
  const action = async (type: 'void' | 'refund') => { if (!selected) return; const deviceActionId = crypto.randomUUID(); if (!online) { await posDb.pendingSaleActions.add({ deviceActionId, saleId: selected.id, storeId: session.storeId, action: type, status: 'pending_sync', createdAt: new Date().toISOString() }); return onNotice(`${type === 'void' ? 'Void' : 'Refund'} queued. It needs approval when back online.`); } const response = await fetch(api(`/sales/${selected.id}/${type}`), { method: 'POST', headers: { Authorization: `Bearer ${session.accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ deviceActionId }) }); if (response.status === 202) { const body = await response.json() as { approval_id: string }; setApproval({ id: body.approval_id, actionType: type, context: `${type === 'void' ? 'Void' : 'Refund'} of ${selected.totalAmount} for sale ${selected.id.slice(0, 8)}.` }); return; } if (!response.ok) return onNotice('Sale action failed.'); const body = await response.json() as { sale: Sale }; setSelected({ ...selected, ...body.sale }); setSales((current) => current.map((sale) => sale.id === body.sale.id ? body.sale : sale)); onNotice(`Sale ${type} completed.`); };
  return <section className="sale-history"><div className="sale-history-head"><div><p className="eyebrow">SALES</p><h2>Sale history</h2></div><Button variant="secondary" onClick={() => void load()}>Refresh</Button></div>{selected ? <Card><Button variant="secondary" onClick={() => setSelected(null)}>Back to sales</Button><h2>Sale {selected.id.slice(0, 8)}</h2><p className="muted">{new Date(selected.createdAt).toLocaleString()} · {selected.paymentMethod}</p><Badge>{selected.status}</Badge><Table><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Discount</th></tr></thead><tbody>{selected.items.map((item) => <tr key={item.id}><td>{item.productId}</td><td className="urp-table-numeric">{item.quantity}</td><td className="urp-table-numeric">${item.unitPrice}</td><td className="urp-table-numeric">${item.discountAmount}</td></tr>)}</tbody></Table><h3>Total ${selected.totalAmount}</h3>{selected.status === 'completed' && <div className="actions"><Button variant="danger" disabled={!online} onClick={() => void action('void')}>Void sale</Button><Button variant="danger" disabled={!online} onClick={() => void action('refund')}>Refund sale</Button></div>}</Card> : <Card><Table><thead><tr><th>Sale</th><th>Time</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id} onClick={() => void open(sale)}><td>{sale.id.slice(0, 8)}</td><td>{new Date(sale.createdAt).toLocaleTimeString()}</td><td className="urp-table-numeric">${sale.totalAmount}</td><td>{sale.paymentMethod}</td><td><Badge>{sale.status}</Badge></td></tr>)}</tbody></Table></Card>}{approval && <SupervisorApprovalModal approval={approval} apiUrl={api} accessToken={session.accessToken} onComplete={(approved) => { setApproval(null); onNotice(approved ? 'Supervisor approved the sale action.' : 'Supervisor rejected the sale action.'); void load(); }} />}</section>;
}
